### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by pjka** [ofeksadlo/lichess-cheat#1]
Traceback (most recent call last):
  File "C:\Users\monty\Desktop\lichess-cheat-master\main.py", line 218, in <module>
    f=open('config.cfg', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'config.cfg'

**Comment by ofeksadlo** [comment]
I have added new config method. You can now download it.

**Comment by pjka** [comment]
thank you sir, 
but one lit problem facing
Traceback (most recent call last):
  File "C:\Users\monty\Desktop\lichess-cheat-master\main.py", line 5, in <module>
    from stockfish import Stockfish
ModuleNotFoundError: No module named 'stockfish'

**Comment by pjka** [comment]
it shows even if i've installed stockfish
